name: Continuous Integration

on:
    workflow_dispatch:
    push:
        branches-ignore:
            - 'main'
            - 'develop'

jobs:
    dependencies:
        uses: ./.github/workflows/dependencies.yml
    code-quality:
        needs: dependencies
        uses: ./.github/workflows/code-quality.yml
